### ISSUE TITLE
Proof in exercise 1.2.4

### ISSUE THREAD

**Issue by ksteensig** [mikinty/Understanding-Analysis-Abbott-Solutions#1]
Hi I'd like to say really nice job making this, it's absolutely impressive.

I took a look at the proof in 1.2.4 (b) because I was confused about the wording. The official solution manual says that a>=0,b<0 and a+b>=0, i.e. all three conditions apply.

Now I may have misunderstood your solution manual, but from what I can see it does not line up with the official solution.

Still, very impressive work you did :+1:.

**Comment by mikinty** [comment]
Oh yeah looks like I misinterpreted it. I'll add a note, but seems like I did more work than I should.

Thanks for pointing this out! Fixed in https://github.com/mikinty/Understanding-Analysis-Abbott-Solutions/commit/7a9c3d0f8de6eca25aa8d20307de76a766e02adf
