### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Andes107** [mikinty/Understanding-Analysis-Abbott-Solutions#3]
It seems that this is a solution for the first edition. Since I am using the second edition, will you accept any edition on either editions?

**Comment by mikinty** [comment]
Hmm I'm pretty sure I used the second edition -- where do you see a discrepancy, and can you point out in detail where it is?

**Comment by mikinty** [comment]
Also if you have any ideas on how to deal with versioning, I would be open to that. 

I would prefer things to stay as one PDF, but if versioning has too many differences, we can maybe split into multiple PDFs.

**Comment by Andes107** [comment]
For example, the proof of Schroeder Bernstein theorem is required in 1.5.11 in my book. But in the main.pdf, it is 1.4.13.  In addition, in my book, 1.5 is cardinality and 1.6 is cantor theorem.![20210116_005708.jpg](https://user-images.githubusercontent.com/61448397/104755720-c7dfab00-5795-11eb-867a-9cd92f6bb18e.jpg)![20210116_005654.jpg](https://user-images.githubusercontent.com/61448397/104755751-d29a4000-5795-11eb-85f9-41648c43660e.jpg)

**Comment by mikinty** [comment]
Ok since the first edition solutions are complete as is, how about we make an additional appendix that explains how the second edition corresponds with the first edition? And if there are any problems that are in the second edition but not in the first, we can do them in the appendix as well.

You can submit a PR for your changes, and let me know if you need help.

**Comment by Andes107** [comment]
Do I need to be a contributor to push changes?

**Comment by mikinty** [comment]
No just fork and make all your changes there. Then when you're ready you can open a PR from your fork to this main repo.

**Comment by Zjmgpk** [comment]
Is there one for the 2nd edition? Sorry if im bothering

**Comment by Andes107** [comment]
No, I am sorry.

**Comment by Zjmgpk** [comment]
That's okay. Thanks at least for this edition.

**Comment by mikinty** [comment]
You are also free to contribute to make a second edition version, perhaps another branch

**Comment by Zjmgpk** [comment]
If I ever can, I know I'd love to. Right now, I've mainly been looking for a solution manual for the 2nd edition due to taking real analysis this coming semester(fall 2021) so I can learn ahead.

**Comment by mikinty** [comment]
Well if you're truly learning ahead, you should be writing your own solutions manual :)

**Comment by mikinty** [comment]
Also, I'm pretty sure there are 2nd edition solution manuals online if you search hard enough, but I don't think you learn as much if you have one because it's hard to force yourself to really try

**Comment by Zjmgpk** [comment]
I've looked around. There are only 1st editions from what I've found.

**Comment by Andes107** [comment]
@mikinty do you think it is possible for you to open a new branch for 2nd edition? In this case, @Zjmgpk can contribute? Hell, I can then contribute also. 
Ever since I have learnt this github repo I have been replicating what you @mikinty have done in first edition but so far I have only detailed the first 2 chapters due to syntactic reasons. Needless to say, @mikinty 's syntax has opened my eyes in latex. And since I am familiar with git instead of github, I have gone off the radar. In particular, I am not so sure how can I merge my work with @mikinty in github. 
@Zjmgpk , so far I have read 5 chapters in Abbott's book, most of which can be solved or found through internet. It is either Google such as some random university lecture material in pdf or mathematics stack exchange post.
Brace yourself, one of the skills to master is learning how to find a solution. Reading and understanding the solution is merely the second if my experience has taught me anything.

**Comment by mikinty** [comment]
Hi @Andes107,

Thank you for your work so far -- merging itself is quite simple on GitHub, and I can help you open the pull request for that.

All I need you to do is
1. Fork the repo, let me know if you need help with this
2. Clone the repo to your local computer
3. Make a new branch 
4. Make the changes 
5. Commit the changes and push to your repo
6. Open a pull request to this repo via GitHub UI 

If this isn't possible, you can DM me what you have and I can put it together, but it would be a good exercise to learn some version control so you can contribute to this repo and others in the future.

**Comment by Andes107** [comment]
Hello @mikinty ,

I have just learnt what is fork and pull request. My 2 cents will be

1. You create a branch for second edition
2. Anyone can then fork your repo to their repo, clone their repo to their local machine
3. Commit and push to second edition branch to their machine and their repo
4. Ask for pull request to the upstream second branch

Now, the problem is, you mentioned about me directly forking and add a new branch that doesn't exist in upstream, according to this [post](https://stackoverflow.com/a/9798239), it seems impossible. But if I catch your drift, it seems possible. Can you elaborate in this regard?

**Comment by filippoitaliano** [comment]
@Andes107 you can fork this repo. At that point you'll have "your" repo. Then you can add and manage branches as you wish in your repo. When you'll want to update @mikinty repo, you'll create a pull request for asking to merge into master (or another branch I think). Keeping a different branch for keeping different material permanently is ugly at my point of view. Still, the decision will be @mikinty responsibility.

**Comment by UlisseMini** [comment]
I've been writing up my solutions https://github.com/ulissemini/understanding-analysis-solutions for the second edition, it isn't done yet but hopefully it's useful to someone! (PS: thanks mikinty I based the latex off this repo <3)

**Comment by mikinty** [comment]
It's been a while but @UlisseMini great work -- let's just keep the 2nd edition as a permanent fork

I don't think I'll be maintaining this repo that much tbh, lots of other interesting projects to do nowadays

LaTeX forever tho
